### ISSUE TITLE
indexer still seems to be re-indexing the full ontology on first use in a session

### ISSUE THREAD

**Issue by bdionne** [bdionne/lucene-search-tab#4]
Should only do a full index once, when used for the first time

**Comment by johardi** [comment]
Could you please describe the full scenario when the issue occurred?

**Comment by bdionne** [comment]
don't have it yet.

**Comment by bdionne** [comment]
We're using the first patch for this (which is why I asked about the second patch and large ontologies)

**Comment by bdionne** [comment]
This is pretty easy to reproduce, just create two ontologies, login to one and it indexes the first time. Same for the second. Now logout of the second and login to the first 
and it will re-index again. Login/out of the same ontology works fine, it's when you switch.

You can see the new indices being created in the filesystem

**Comment by johardi** [comment]
This is the log when I tried to run your scenario.
-  I logged in as a user and opened 2 projects. The search manager built both indexes for the first time. Notice the associated index directories and the ontology.

```
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-a5cc6a97-9c277e1d 
Building index 
... collecting items to index from http://protege.stanford.edu/plugins/owl/owl-library/koala.owl/1.0.0 
... found 111 items to index 
... start writing index 
... built index in 284 ms 
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-7ddb6a9b-9c27bd6d 
Building index 
... collecting items to index from http://www.co-ode.org/ontologies/pizza/pizza.owl 
... found 1148 items to index 
... start writing index 
... built index in 262 ms 
```
- I did a switch between Koala and Pizza projects using the ontology selector in Protege (the upper combo box bar). The search manager reloaded the associated index directory.

```
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-a5cc6a97-9c277e1d 
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-7ddb6a9b-9c27bd6d 
```
- I reopened Koala project (koala.owl) after I logged out and logged in (relogin). The search manager just loaded the index.

```
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-a5cc6a97-9c277e1d 
```
- I reopened Pizza project (pizza.owl) after relogging in. The search manager just loaded the index.

```
Initializing index delegator 
Opening index directory at /Users/jhardi/.Protege/lucene/ProtegeIndex-7ddb6a9b-9c27bd6d 
```

**Comment by bdionne** [comment]
I didn't use the ontology switcher, just logged out of ont1 and logged in to ont2

Was your scenario running with the nci-0.99 tag? If not which version of the code did you run?

**Comment by johardi** [comment]
This one is not nci-0.99. It's from our client-server repo. Oww wait, do you open this issue just for your reminder?

**Comment by bdionne** [comment]
I opened it because the user reported it, and the other issue in your repo was already closed.

The nci-0.99 is using the first patch you did, not the second that was more involved

**Comment by johardi** [comment]
You need the second patch to make it really work

**Comment by bdionne** [comment]
oh, so the first wasn't the fix? Ok, thanks, I'll see if I can cherry-pick that one when I get a chance. That one touches 3 repos though and one is protege-client, so perhaps I'll just poke at this version some more. I'm also not convinced yet about the mock ontology.

**Comment by bdionne** [comment]
I tried this second patch, minus the changes to the protege-client, and it still didn't work. The root cause is that we're using the  hash code of ontology id IRI as a preferences key for the index records. That works fine _unless_ you have two projects that use the same ontology. This happened to be the scenario in my test case, where I cloned foo to make bar and used the same owl file. Once one of them changes, the checksums will no longer match and a new index directory created.

Not sure yet what the answer is for this, but it's enough of an edge case that we can leave it for now. Having another additional bit of information used to generate the index record key is the obvious answer but what bit to use I'm not sure of. The search is independent of the protege-client so using the project id is probably not the best.

With respect to the protege-client change, I'm wondering if listening for ontology changes is too fine-grained. I have a version I'll push later that uses the `HistoryManager` instead. This allows us to inject the SessionRecorder as the `HistoryManager` and better control the indexer. 

Another problem that occurred to me that both solutions face is that shutting off events while loading the snapshots and updating the history from the server misses the case where some of those updates come from other users and do need to be indexed.

In any event, I opened a separate [issue](https://github.com/bdionne/lucene-search-tab/issues/5) for this as there is a performance hit when editing with the incremental indexer.

**Comment by johardi** [comment]
I agree with your view in paragraph 1 & 2. In general, it's a 1-to-1 indexing approach, meaning one index directory is for one ontology only. You can reuse the directory if the input ontology is the same, or rebuild if necessary.

```
I'm wondering if listening for ontology changes is too fine-grained. I have a version
I'll push later that uses the HistoryManager instead.
```

I'm not convinced to say the SearchManager should listen to the HistoryManager.

```
[...] and updating the history from the server misses the case where some of those
updates come from other users and do need to be indexed.
```

Any reason why we shouldn't index the updates from other users? Other users might want to find the terms created by some others, don't they?

**Comment by johardi** [comment]
I think the core functionality of the search manager is already there. I think what you observed right now as limitations in the search manager is due to missing key features in protege-client. For example, protege-client doesn't support yet the notion of "local copy" or "local versioning". Due to lack of this feature, the search will always reindex the incoming ontology rather than be updating it with the latest changes. In addition, with the local copy, we can localize the index directory such that it won't interfere with other ontologies even though they are using the same ID.

Another missing key feature is the notion of "open a local versioning". Right now every time users select "Open from Protege OWL Server...", the action is similar to say `git clone` so don't be surprised if all client modules will treat the incoming ontology as a fresh new ontology. We need to have a local versioning environment such that "Open a local version..." is different from "Open from Protege OWL Server..."

**Comment by bdionne** [comment]
I agree, with one exception. We need a way to control the incremental indexer. A large complex operation might involve 100s of edits and in the end be cancelled. It's a lot of useless work for the indexer.

**Comment by bdionne** [comment]
closing this, the solution will be making the search indexing operate on projects rather than ontologies. We need to support sandboxing, having play projects than make use of the same ontology as a real project. Indices should be isolated
