### ISSUE TITLE
Incremental indexing interacts poorly with editing

### ISSUE THREAD

**Issue by bdionne** [bdionne/lucene-search-tab#5]
In a large ontology, each edit causes incremental indexing to occur. This seems to take unusually long, not sure of the root cause. Indexing is based on ontology changes, which perhaps is too fine grained.

This is quite noticeable, .eg. in doing a retirement that has 30 to 40 references to repair. If at the end of the process the user choose to cancel the retirement, all of the edits that get reversed also cause the indexer to remove the records.

**Comment by bdionne** [comment]
I took a pass at basing the incremental indexing on the [`HistoryManager`](https://github.com/bdionne/lucene-search-tab/commit/5f28130b1e1da818ae755001c3408d2e62ade3d0). This allows us to use the `SessionRecorder` to better control the indexing. Perhaps incremental indexing needs it's own interface, but for now this allows us to experiment with it. If the client/server plugins are not loaded it will behave exactly as it does now since the `UndoListener` allows access to the change stream

**Comment by johardi** [comment]
I'm not sure with the idea saying the SearchManager should listen to the HistoryManager. And wouldn't be calling `getLoggedChanges()` will obtain the whole changes in the undo stack? Which means the search manager will always re-update the previous changes?

**Comment by bdionne** [comment]
yes for sure, this is more a placeholder, since for now the `SessionRecorder` can control whether the SearchManager gets those events. The `SessionRecorder` is cleared after a commit occurs. The idea I'm after is a way to easily control the SearchManager so that it doesn't just receive all ontology change events for indexing.

I'm think that the SearchManager needs an interface internally, like `IncrementalIndexer` that users can control, or maybe, even simpler, a static method one can call to disable indexing as we call on the `SessionRecorder`

**Comment by bdionne** [comment]
The simplest solution for now seems to be adding the [ability](https://github.com/bdionne/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/model/search/SearchManager.java#L41) to enable/disable incremental indexing and allow users to call it on demand. 

In our case we can call the indexer after committing changes which will remove the chattiness during long complex operations.

**Comment by bdionne** [comment]
Adding the ability to disable automatic indexing on all ontology changes, and calling the indexer explicitly after a commit, the GUI still freezes up and is not responsive while the indexing is on-going.

**Comment by bdionne** [comment]
The issues appears to be we are computing a [checksum](https://github.com/bdionne/lucene-search-plugin/blob/master/src/main/java/org/protege/editor/search/lucene/LuceneIndexPreferences.java#L399-L403) of the ontology every time an index occurs. Profiling indicates this computation is very expensive on large ontologgies

**Comment by bdionne** [comment]
This is resolved, the indexer is now programmatically disabled and called explicitly when changes are committed. We also removed the checksum calculation that was being performed on the entire ontology each time the indexer ran.

Performance is acceptable
